# database/seed_corpus.py

"""
Seed the PostgreSQL database for Echo2Equation.

What this script does:
----------------------
1. Creates the `corpus` table if it does not already exist.
2. Creates the `feedback` table if it does not already exist.
3. Safely adds missing feedback columns using ALTER TABLE.
4. Reads data/full_dataset.jsonl.
5. Inserts spoken-text and LaTeX pairs into the `corpus` table.
6. Skips duplicate corpus rows using ON CONFLICT.

Why this is useful:
-------------------
The `corpus` table is used by the application as a searchable collection
of known correct spoken-math-to-LaTeX examples.

The `feedback` table stores user responses such as:
- whether the model prediction was correct
- what the model generated
- what corrected LaTeX the user provided
- whether the user retried or cleared the attempt

Run from project root:
----------------------
python database/seed_corpus.py
"""

import json
import os
import uuid
from pathlib import Path

import psycopg2


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

# Final cleaned dataset used by the project.
DATA_FILE = Path("data/full_dataset.jsonl")


# ---------------------------------------------------------------------
# Database configuration
# ---------------------------------------------------------------------
# These defaults match your Docker Compose PostgreSQL service.
# They can be overridden using environment variables if needed.

DB_USER = os.getenv("DB_USER", "echo2eq")
DB_PASS = os.getenv("DB_PASS", "echo2eq_pw")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "echo2eq_db")


# ---------------------------------------------------------------------
# Table creation SQL
# ---------------------------------------------------------------------

DDL_CORPUS = """
CREATE TABLE IF NOT EXISTS corpus (
  id UUID PRIMARY KEY,
  text TEXT NOT NULL,
  latex TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (text, latex)
);
"""


DDL_FEEDBACK = """
CREATE TABLE IF NOT EXISTS feedback (
  id UUID PRIMARY KEY,

  -- User input or Whisper transcript
  transcript_text TEXT,

  -- LaTeX generated by the model
  generated_latex TEXT,

  -- Correct LaTeX entered by the user if model output was wrong
  corrected_latex TEXT,

  -- True  = user accepted model output
  -- False = user said output was incorrect
  -- NULL  = no final correctness decision
  correct BOOLEAN,

  -- Whether retry/suggestion logic was used
  retried BOOLEAN NOT NULL DEFAULT FALSE,

  -- Whether the user chose to start again / clear the attempt
  record_again BOOLEAN NOT NULL DEFAULT FALSE,

  -- Optional metadata
  audio_path TEXT,
  visual_path TEXT,
  corpus_id UUID,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
"""


# This migration keeps old databases compatible.
# If the table already existed before we added new columns,
# ALTER TABLE safely adds missing columns without deleting data.
DDL_FEEDBACK_MIGRATION = """
ALTER TABLE feedback
ADD COLUMN IF NOT EXISTS corrected_latex TEXT,
ADD COLUMN IF NOT EXISTS audio_path TEXT,
ADD COLUMN IF NOT EXISTS visual_path TEXT,
ADD COLUMN IF NOT EXISTS corpus_id UUID;
"""


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

def get_connection():
    """
    Create and return a PostgreSQL connection.
    """
    return psycopg2.connect(
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASS,
        host=DB_HOST,
        port=DB_PORT,
    )


def ensure_tables(cur) -> None:
    """
    Create required tables and apply safe migrations.
    """
    cur.execute(DDL_CORPUS)
    cur.execute(DDL_FEEDBACK)
    cur.execute(DDL_FEEDBACK_MIGRATION)


def load_dataset_rows(path: Path):
    """
    Yield valid rows from the JSONL dataset.

    Expected row format:
        {"spoken": "...", "latex": "..."}

    Invalid or incomplete rows are skipped.
    """
    with path.open("r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                obj = json.loads(line)
            except json.JSONDecodeError as exc:
                print(f"[skip line {line_number}] Invalid JSON: {exc}")
                continue

            spoken = (obj.get("spoken") or "").strip()
            latex = (obj.get("latex") or "").strip()

            if not spoken or not latex:
                print(f"[skip line {line_number}] Missing spoken or latex field")
                continue

            yield spoken, latex


# ---------------------------------------------------------------------
# Main script
# ---------------------------------------------------------------------

def main() -> None:
    """
    Seed the corpus table and ensure feedback schema is ready.
    """
    if not DATA_FILE.exists():
        print(f"Seed file not found: {DATA_FILE.resolve()}")
        return

    conn = get_connection()
    conn.autocommit = False
    cur = conn.cursor()

    try:
        # Create tables and add any missing columns.
        ensure_tables(cur)
        conn.commit()

        insert_sql = """
            INSERT INTO corpus (id, text, latex)
            VALUES (%s, %s, %s)
            ON CONFLICT (text, latex) DO NOTHING;
        """

        processed = 0

        for spoken, latex in load_dataset_rows(DATA_FILE):
            cur.execute(insert_sql, (str(uuid.uuid4()), spoken, latex))
            processed += 1

            # Commit in batches so large seeding is safer.
            if processed % 1000 == 0:
                conn.commit()
                print(f"[progress] processed rows: {processed:,}")

        conn.commit()

        cur.execute("SELECT COUNT(*) FROM corpus;")
        total = cur.fetchone()[0]

        print("Done.")
        print(f"Dataset rows processed: {processed:,}")
        print(f"Corpus total rows in DB: {total:,}")

    except Exception as exc:
        conn.rollback()
        print(f"Database seeding failed: {exc}")
        raise

    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    main()